-- Create the paynexus user with proper permissions
CREATE USER paynexus WITH PASSWORD 'paynexus123';
ALTER USER paynexus CREATEDB;
GRANT ALL PRIVILEGES ON DATABASE paynexus TO paynexus;
GRANT ALL ON SCHEMA public TO paynexus;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO paynexus;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO paynexus;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO paynexus; 